version: '3.8'

services:
  # Backend service (Go API)
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_PATH: "todos.db"
      PORT: "8080"
    volumes:
      - ./todos.db:/app/todos.db
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/todos"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Frontend service (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  todo-network:
    driver: bridge 