version: '3.8'

services:
  # Backend service (Go API)
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/todos.db
      - PORT=8080
    volumes:
      - todo_data:/data
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/todos"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Named volumes for data persistence
volumes:
  todo_data:
    driver: local

# Network for service communication
networks:
  todo-network:
    driver: bridge 